git:
  depth: false
language: rust
sudo: required
dist: xenial
addons:
    apt:
        packages:
            - libssl-dev
            - g++
cache: cargo
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f

before_script:
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test


after_success: |
  cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
