[package]
name = "glisp"
version = "0.0.1"
authors = ["Jordan Osborn <jordanosborn0@gmail.com>"]
edition = "2018"
exclude = [
    "test.glisp"
]
license = "MIT"
description = "A lisp for genetic programming"
documentation = "..."
homepage = "https://github.com/jordanosborn/Glisp"
repository = "https://github.com/jordanosborn/Glisp"
readme = "README.md"

[dependencies]
